---
- hosts:  all
  become: true
  vars:
    AnsibleVersion: "2.9.17"
  tasks:
  - name: yum update
    yum:
      update_cache: yes
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    delay: 10
    retries: 12
    become_user: root
  - name: Install python3-pip
    yum:
      name: python3-pip
      state: present    
  - name: Install Ansible
    pip:
      name: ansible
      version: "{{AnsibleVersion}}"
      state: present

  # - name: Add ansible repository.
  #   apt_repository: repo='ppa:ansible/ansible'   
  # - name: Update apt cache.
  #   apt: update_cache=true cache_valid_time=86400    
  # - name: Install Ansible.
  #   apt:
  #     name: ansible
  #     state: present
