---
- hosts:  all
  become: true
  vars:
    AnsibleVersion: "2.9.17"
  tasks:
  - name: apt-get update
    apt:
      update-cache: yes
  - name: Apply updates for Debian/Ubuntu
    apt:
      upgrade:  dist
      autoremove: yes
      state: latest
    register: patched
    delay: 10
    retries: 12
    become_user: root
    until: patched is successful
  - name: Install sshpass, requirement for ansible
    apt:
      name: sshpass
      state: present
  - name: Ensure dirmngr is installed (gnupg dependency).
    apt:
      name: dirmngr
      state: present    
  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present    
  - name: Install Ansible
    pip:
      name: ansible
      version: "{{AnsibleVersion}}"
      state: present

  # - name: Add ansible repository.
  #   apt_repository: repo='ppa:ansible/ansible'   
  # - name: Update apt cache.
  #   apt: update_cache=true cache_valid_time=86400    
  # - name: Install Ansible.
  #   apt:
  #     name: ansible
  #     state: present
